- components/Card.vue
- components/Stats.vue
- store/index.js
Made the stats component fetch data from the API
> Make the stats component dynamic

- components/CheckBox.vue
- components/Contributors.vue
- components/InputsSection.vue
- components/PaginationBar.vue
- components/RadioButton.vue
- components/TopDevelopers.vue
- components/UserCard.vue
- store/index.js
1. Fixed the image filter, it didn't work on fetched images from the API
2. The top contributors component now fetch users from the API
3. Enabled sorting using the radio buttons in the filter section 
4. Made the pagination bar dynamic
> Make the top contributors section dynamic

- components/PaginationBar.vue
- components/Stats.vue
- store/index.js
Fetch the users from the API based on the current page from the pagination bar
> Fetch users based on the current page

- components/PaginationBar.vue
- components/RadioButton.vue
- store/index.js
Make the request for fetching the users maintain the current page while changing the sort by variable
> Fix sorting to maintain the current page

- layouts/global.css
Made the web pages use the client local fonts until the fonts get loaded from the server then swap them
> Add font-display swap to the fonts

- package-lock.json
- package.json
- pages/index.vue
Added lazy hydration for the stats and the top contributors' components to decrease the time required to interactivity for the user
> Add Lazy hydration

- pages/index.vue
Made the home page import the stats and the top contributors' components dynamically when visible
> Use dynamic imports for the components in the home page

- package.json
Added a script in the package.json file to build a modern build, now the server will check the browser version based on the user agent and serve the corresponding modern or legacy bundle.
> Add the modern build script in package.json

- components/PaginationBar.vue
- components/RadioButton.vue
- components/Stats.vue
- nuxt.config.js
Make the website use environment variables
> Create axios environment variables

- nuxt.config.js
Added the env object in the nuxt.config file to make the website use the environment variable
> Add the env object in the nuxt config file

- nuxt.config.js
- package-lock.json
- package.json
Added the REST API host to the proxy configuration in the nuxtJS  configuration file
> Add the proxy configuration to the nuxt configuration

- nuxt.config.js
- package-lock.json
- package.json
Created a health-check  for the nuxt configuration file
> Create a Healthcheck

- components/PaginationBar.vue
- nuxt.config.js
The website now has a better SEO by:
1- Changing the <a> HTML tags to the <button> HTML tag Making them, didn't need <a> tags because we didn't reference a resource
2- Changed the title of the document
3- Added the document meta description
> Optimize SEO

- components/Card.vue
- components/TheFooter.vue
- components/TheHeader.vue
Added explicit width and height for the images to reduce layout shifts and improve CLS.
> Set explicit width and height for the images

- components/Contributors.vue
Implemented the users ranking by adding conditional rendering based on the sort by method
> Implement the users ranking feature

- components/Contributors.vue
- components/FilterSection.vue
This pull request is a fix for this issue #37
> Change the behavior of the filter header

- components/Hero.vue
- components/Stats.vue
- components/TopDevelopers.vue
- components/UserCard.vue
This is a fix for issue number #44
> Fix the text header semantics

- components/UserCard.vue
Gave the rank element a fixed width, this fixed issue number #43
> Fix the rank element width for the user card

- components/Contributors.vue
- components/PaginationBar.vue
- components/PeriodDropdown.vue
- components/RadioButton.vue
- components/Stats.vue
- components/TopDevelopers.vue
- store/index.js
Refactor and update the website to use the latest filtering feature from the updated REST API
> Implement filtering feature

- .dockerignore
- .drone.yml
- .gitignore
- Dockerfile
- update dockerignore
- update gitignore
- update drone file, now uses drone templates
- optimized dockerfile
- add user roles
- add multistage
- add args and env var
> Optimized docker file

- .env.sample
- .gitignore
- Dockerfile
- docker-compose.yaml
- nuxt.config.js
add a new env.sample
exclude env.sample form the gitignore 
update all env var to new standard
> Update env var

- components/TopDevelopers.vue
- components/TopOrganizations.vue
- package-lock.json
- package.json
- tailwind.config.js
Update the tailwind version from 4.2.0 to 5.3.2
> Upgrade tailwind
